import { Vazirmatn } from 'next/font/google'

export const metadata = {
  title: 'پژواک',
  description: 'Generated by Next.js',
}

const vazirmatn = Vazirmatn({subsets:['latin'], fallback:['sans serif']})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir='rtl'>
      <body className={vazirmatn.className}>{children}</body>
    </html>
  )
}
