import { ProviderLayout } from "@/layouts/provider-layout";
import { Vazirmatn } from "next/font/google";
import { Roboto } from "next/font/google";
export const metadata = {
  title: "پژواک",
  description: "Generated by Next.js",
};

const vazirmatn = Vazirmatn({ subsets: ["latin"], fallback: ["sans serif"] });
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirmatn.className}>
        <ProviderLayout>{children}</ProviderLayout>
      </body>
    </html>
  );
}
